site_name: libCacheSim Python Documentation
site_url: https://cachemon.github.io/libCacheSim-python/
repo_url: https://github.com/cacheMon/libCacheSim-python
repo_name: cacheMon/libCacheSim-python

docs_dir: src

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - API Reference: api.md
  - Examples: examples.md

theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode  
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Open Sans
  features:
    - header.autohide
    - navigation.tabs
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate

extra_css:
  - ../stylesheets/extra.css

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            Home: 首页
            Quick Start: 快速开始
            API Reference: API参考
            Examples: 使用示例

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - codehilite
  - toc:
      permalink: true
  - tables
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cacheMon/libCacheSim-python

copyright: Copyright &copy; 2025 libCacheSim Team