name: Build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Prepare
        run: bash src/libCacheSim/scripts/install_dependency.sh

      - name: Build main libCacheSim project
        run: |
          pushd src/libCacheSim
          cmake -G Ninja -B build
          ninja -C build
          popd

      - name: Build libCacheSim-python
        run: |
          pip install -e .[dev]

      - name: Run tests
        run: |
          python -m pytest tests/

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-docs-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-docs-

      - name: Install documentation dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Test documentation build
        run: |
          cd docs
          mkdocs build --clean --strict